import { ImageResponse } from "next/og";

/**
 * Site-wide default OpenGraph image. Served at /opengraph-image and used
 * when a page doesn't define its own `opengraph-image.tsx`. Generated by
 * the edge runtime at request time so we can tweak the design without
 * re-baking assets.
 *
 * Routes that need their own image (individual case studies, articles)
 * add an `opengraph-image.tsx` inside their route folder.
 */
export const alt = "Webgro · Shopify, WordPress, and AI tools. One studio.";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#07080C",
          padding: 72,
          fontFamily: "Inter, sans-serif",
          color: "#EDEFF4",
          position: "relative",
        }}
      >
        {/* Ambient gradient blob in the top-right */}
        <div
          style={{
            position: "absolute",
            top: -200,
            right: -120,
            width: 640,
            height: 640,
            borderRadius: 9999,
            background:
              "radial-gradient(circle at center, rgba(124,58,237,0.45) 0%, rgba(45,141,255,0.22) 35%, transparent 70%)",
            filter: "blur(40px)",
          }}
        />

        {/* Gradient accent bar */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 20,
          }}
        >
          <div
            style={{
              height: 6,
              width: 220,
              background:
                "linear-gradient(90deg, #2D8DFF 0%, #7C3AED 50%, #00C9A7 100%)",
              borderRadius: 999,
            }}
          />
          <div
            style={{
              fontSize: 20,
              letterSpacing: 6,
              textTransform: "uppercase",
              color: "#6B7A99",
              fontFamily: "monospace",
            }}
          >
            [ Webgro · 2026 ]
          </div>
        </div>

        {/* Big title */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 28,
            zIndex: 1,
          }}
        >
          <div
            style={{
              fontSize: 108,
              fontWeight: 800,
              lineHeight: 1,
              letterSpacing: -2,
              color: "#EDEFF4",
              display: "flex",
              flexWrap: "wrap",
              alignItems: "flex-end",
              gap: 16,
            }}
          >
            <span>We&nbsp;build&nbsp;websites.</span>
            <span
              style={{
                background:
                  "linear-gradient(90deg, #2D8DFF 0%, #7C3AED 50%, #00C9A7 100%)",
                backgroundClip: "text",
                color: "transparent",
                fontStyle: "italic",
                paddingRight: 20,
              }}
            >
              And the systems behind them.
            </span>
          </div>
          <div
            style={{
              fontSize: 30,
              lineHeight: 1.35,
              color: "#9AA6BC",
              maxWidth: 900,
            }}
          >
            Shopify, WordPress, and production AI tools. One studio in
            Bracknell.
          </div>
        </div>

        {/* Footer: wordmark + meta */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
            zIndex: 1,
          }}
        >
          <div
            style={{
              fontSize: 52,
              fontWeight: 800,
              letterSpacing: -1,
              color: "#EDEFF4",
            }}
          >
            Webgro
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              fontSize: 18,
              letterSpacing: 4,
              textTransform: "uppercase",
              color: "#6B7A99",
              fontFamily: "monospace",
            }}
          >
            <div
              style={{
                width: 10,
                height: 10,
                borderRadius: 999,
                background: "#00C9A7",
              }}
            />
            webgro.co.uk
          </div>
        </div>
      </div>
    ),
    size,
  );
}
